#!/bin/sh
if [ "$#" -gt 1 ]; then
    is_branch_checkout="$3"
else
    is_branch_checkout="$1"
fi

# Only run stow after branch checkouts, not file checkouts.
if [ "$is_branch_checkout" -ne 1 ]; then
    exit
fi

"$(git rev-parse --show-toplevel)/stow.sh"
