[misc]
pre_sudo = true
assume_yes = true
display_time = true
disable = ["firmware"]

[git]
repos = []
# Only pull the repos listed above.
pull_predefined = true
# Arguments to pass Git when pulling Repositories
arguments = "--rebase --autostash"

[linux]
# I use paru for AUR but this option feels more evergreen.
arch_package_manager = "autodetect"
